version: '3.4'

services:
  nginx:
    image: nginx:alpine
    command: nginx -g "daemon off;"
    ports:
    - "80:80"
    depends_on:
    - django
    volumes:
    - staticfiles:/var/www/app/staticfiles
    - ./project/nginx.conf:/etc/nginx/conf.d/default.conf

  django:
    build: ./project
    command: gunicorn core.wsgi -b 0:8000 --log-level debug --capture-output
    volumes:
    - staticfiles:/usr/src/app/staticfiles
    environment:
    - DEBUG=1
    ports:
    - "8000:8000"
    depends_on:
    - redis

  celery:
    build: ./project
    entrypoint: celery
    command: ["worker", "--app=core", "--loglevel=info"]
    depends_on:
    - django
    - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build: ./project
    command: flower -A core --port=5555 --broker=redis://redis:6379/0
    ports:
    - "5555:5555"
    environment:
    - DEBUG=1
    depends_on:
    - django
    - redis
    - celery

volumes:
  staticfiles: